### ISSUE TITLE
create keyword track bins with language filters?

### ISSUE THREAD

**Issue by theoaraujo** [digitalmethodsinitiative/dmi-tcat#100]
Hi guys,

Do you have plans to enable creating keyword tracking bins that filter by language (e.g. just Dutch, or French etc.)?

Thanks!

**Comment by ErikBorra** [comment]
We have considered doing so. The problem is that Twitter's API is set up [in such a way](https://dev.twitter.com/streaming/overview/request-parameters#language) that it's all or nothing: either all query bins capture tweets with a specific (set of) languages, or all query bins capture tweets in all languages. We could, however, introduce a filter in analysis/index.php so that you can make a sub-collection of tweets which are marked by Twitter's API as being of a specific language.
