### ISSUE TITLE
Best MySQL Storage/MGMT for Rasp Pi

### ISSUE THREAD

**Issue by joep1** [digitalmethodsinitiative/dmi-tcat#110]
Hey,

So you might remember my saga of getting DMI-TCAT onto a pi... which I eventually managed.

Sure enough, it is great at collecting but not at processing once you want to download your data.

Therefore, can I ask a general question for an idea I had - will this work/any reason why not?:

I was thinking:

I will setup the MySQL to run off external storage on the Pi (e.g. 4gb USB stick or whatever it takes) and then setup a second instance of DMI-TCAT running on my Linux Desktop to also run off the same USB stick...

Rasp Pi then collects data onto USB stick and when I am ready I can switch the USB stick off the Pi and onto the Desktop... load up my local Desktop version of DMI-TCAT, running off a DB on the USB stick and then process the data with my Desktop powers...

So:

1) Does this sound feasible? Any reason it might not work?

2) I hear there are issues with MySQL going over say 1gb... I can't imagine how much twitter data that would be, but hypothetically, how do you guys deal with data sets if they get bigger than that? How do you manage them and process them? I've never dealt with big sets like that as the most I have collected with DMI-TCAT is about 200k tweets.

**Comment by ErikBorra** [comment]
1) yes that should be feasible. Just make sure MySQL on both machines has the (mounted) USB as the mysql data dir.
2) we have MySQL db's of 100's of GBs running without a problem. Maybe @dentoir has some suggestions for optimising MySQL for these instances.

**Comment by joep1** [comment]
Awesome. I'll report back if I get around to it and it works!

**Comment by dentoir** [comment]
I'm very curious whether this raw binary multi-access worked, considering we are talking 32bit <-> 64bit. MyISAM tables are supposed to be machine independent though, so this will be an interesting test.

Optimizations:

If you don't intend to capture more data after you've captured the data on the raspberry pi, you could consider using the myisampack utility to compress your data and increase access speeds on the desktop.

Some general MySQL tips (for a TCAT MySQL server):

Increase your key_buffer_size in /etc/mysql/my.cnf to somewhere between 20-50% of system memory (keep something for the disk cache).
Use the mysqltuner.pl script (http://mysqltuner.pl/) to check your setup for possible tweaks.
Do not be afraid to overcommit memory (a bit) if you are a single user on your system. The script reports memory problems with the scenario of lots of connections to your server.

If you do a lot of complex queries besides text searches with date ranges, especially GEO queries, you will always end up using temporary files on disk. If your /tmp directory is on a physical storage instead of virtual memory, consider using a tmpfs for this (most Linux distro's like Debian are configured this way already). You can find documention on this topic online.
