### ISSUE TITLE
Mysql extension deprecated

### ISSUE THREAD

**Issue by ampossel** [digitalmethodsinitiative/dmi-tcat#155]
Dear,

When trying to analyse tweets, I get the next error. Could anyone tell me what the problem is here?

**Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /volume1/web/dmi-tcat/analysis/common/functions.php on line 849 **

Thank you in advance, 
Anne-Marieke

**Comment by ErikBorra** [comment]
Hi Anne-Marieke,

some of the mysql queries in TCAT are still done through mysql_query instead of PDO. While this generates warnings it is not an error and we have tested that TCAT works fine up till PHP 5.6. Nothing to worry about.

You can suppress these warnings from your error log by adjusting [error_reporting](http://php.net/manual/en/function.error-reporting.php) in config.php

Best,

Erik

**Comment by ErikBorra** [comment]
As this is already addressed in issue #7 I'm closing this issue.
