### ISSUE TITLE
Small issue with encoding quotation marks in data exports from TCAT

### ISSUE THREAD

**Issue by Snurb** [digitalmethodsinitiative/dmi-tcat#180]
Hi,

TCAT is usually very good at encoding quotation marks in its CSV/TSV exports, which is important for the further processing of such files, e.g. in BigQuery. However, it trips up very occasionally when the original text contains the character sequence \" (rather than just "). See e.g. the tweet at [https://twitter.com/infonote/status/718395999312478208](https://twitter.com/infonote/status/718395999312478208): 

> Ira Losco will sing \"Walk On Water\" for Eurovision 2016 http://dlvr.it/L0j7GX

This is converted into the following line in the fullExport TSV:

> 718395999312478208	1460113928	"2016-04-08 21:12:08"	infonote	"Ira Losco will sing \"Walk On Water\" for Eurovision 2016 https://t.co/l8kUTQgQfD https://t.co/HsregnyaJB"	low	0			0	0	0	en				"<a href=""http://dlvr.it"" rel=""nofollow"">dlvr.it</a>"				715077179378311168	"Peter Mus"	0			http://abs.twimg.com/sticky/default_profile_images/default_profile_6_normal.png			en-gb	316	2	40	0	1		"2016-03-30 17:24:19"

The correct encoding of the tweet text in a TSV or CSV export should escape the quotation marks in the tweet text by doubling them, to

> "2016-04-08 21:12:08"	infonote	"Ira Losco will sing \""Walk On Water\"" for Eurovision 2016 https://t.co/l8kUTQgQfD https://t.co/HsregnyaJB"

(BigQuery, for one, complains about the incorrect quotation marks when trying to import the TCAT export into a table...)

A very obscure error, but it would be great if this could be fixed...

Axel Bruns

**Comment by dentoir** [comment]
Hi @Snurb,

The export code is actually relying on PHP's fputcsv() - and your example triggers the undocumented behaviour of not-doubling the field enclosure character (") whenever the escaping character (\) is directly in front of it. It interpretes the input string to have been escaped already, instead of double enclosing it, as you would expect. The escaping character parameter of the fputcsv() function is apparantly used to _scan_ for this character character in the string, rather than to use this character to produce escaped entities (only quotes are escaped by adding more quotes ("") is my assumption). The documentation of fputcsv() is absent, but at least one developer noticed this same peculiarity:
http://php.net/manual/en/function.fputcsv.php#105110

Some example code to prove this is the functions behaviour:

$id = 1000;     // just some number
$text =  "Ira Losco will sing \\\"Walk On Water\\\" for Eurovision 2016 http://dlvr.it/L0j7GX";
fputcsv(STDOUT, array( $id, $text ), "\t");

Now I'm happy to fix this bug, but I would love to keep using the fputcsv() function and I'm afraid it **demands** defining an escaping character, or it will default to (\)

My suggested solution is to either str_replace \\" with \" (but we will lose the visibility of \), or using the special null-character as an escape character.

fputcsv(STDOUT, array( $id, $text ), "\t", '"', "\0");

Not sure whether the Twitter allows tweeting of null characters, otherwise the next tweet will produce an identical problem (I tested this): "Ira Losco will sing \0\"Walk On Water\0\" for Eurovision 2016 http://dlvr.it/L0j7GX"

Anyway, I'll test both options.

**Comment by dentoir** [comment]
Found the bug here, and my suggested work-around ;-)

https://bugs.php.net/bug.php?id=43225

Meanwhile, I haven't found any null-characters in millions of tweets, so we should go for that work-around.

**Comment by dentoir** [comment]
This is now fixed in master, tested with your tweets. I looked through millions of tweets, didn't see any null characters.

**Comment by Snurb** [comment]
G'day !

Brilliant – thank you for this !
