### ISSUE TITLE
Duplicates data when you use search and track?

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#181]
I think its duplicating data when i use simultaneous track and search process on the same querybin, it's possible?

any of both process, verify before insert the id into database? 

i think on _tweets is not posible,(becasue the id is unique) but in _hashtags OR _urls, etc its possible, any idea?

Regards!

**Comment by ErikBorra** [comment]
Hi @psegovias,

search will never insert something that is already present in the query bin. Afaik, track does not do this extra check, the reason being that we assume that track never provides doubles. Running a search on a track bin is only useful for bootstrapping a bin with (some) historical data. A track will provide all tweets, given that you do not run into rate limits. The search API, however, will only return the 'most relevant' tweets - whatever that is (it's not specified in the API documentation). 

So, if you want to use search and track, use search before you start tracking to bootstrap a bin with some historical data, then start track after the search script has ended. This way you should never get doubles.

Best,

Erik

**Comment by psegovias** [comment]
Thanks @ErikBorra i do like it you say.

**Comment by psegovias** [comment]
Hi again @ErikBorra  if i want tracking with "track" and "search" (both at the same time) how i can make "track" do the extra check before insert new tweet?

regards!

**Comment by ErikBorra** [comment]
Run the search script first (in /var/www/dmi-tcat/capture/search), thus creating a new bin. When finished, go to the admin panel in your browser and click 'start' to continue tracking the bin. Note that for high volume keywords, the search API will not provide all tweets (and Twitter does not specify what kind of tweets are provided or left out).

**Comment by psegovias** [comment]
is possible tweets are left out, will capture a couple hour later or days?

for example:

run search and get 1000 tweets and then start track, next day i have 1100 tweets and use search again, and capture 100 new tweets, now i have 1200 tweets, maybe that 100 tweets who api left out on the first run search become avaible days or hour later?

im facing that problem...

**Comment by ErikBorra** [comment]
Unless you are running into rate limits track should provide you all tweets for a given set of keywords. Are your search and track phrases exactly the same? Op 28 jun. 2017 15:52 schreef Patricio Segovia <notifications@github.com>:is possible tweets are left out, will capture a couple hour later or days?
for example:
run search and get 1000 tweets and then start track, next day i have 1100 tweets and use search again, and capture 100 new tweets, now i have 1200 tweets, maybe that 100 tweets who api left out on the first run search become avaible days or hour later?
im facing that problem...

**Comment by psegovias** [comment]
i have not rate limits, and i have the same keyword on search and stream.

is very easy to replicate, if you use a low keyword volume: run search, when finish, run track and wait some hours.. and then use search again (with track running) and u will capture (depending of keyword) a couple of tweets that has not been provided in the first capture.

Another example is use search on random keyword and when finish go to db and get the last tweet id capture, edit search file and add max_id:XXXX and wait couple hour and run search again, with max_id:  you prevent new tweets will be capture, but some how , api will make available a couple tweets not capture at the first time.

That is why im tracking with track and search at the same time, buy i cant find why this happen.

**Comment by ErikBorra** [comment]
We have tested track vs search multiple times in the past and never got new things in search when a track was already running. Twitter might have changed, although I doubt it. 

It is not clear, however, whether your issue is related to running search multiple times, or whether it is related to running track and then getting new tweets via search. The latter should never happen - as 'track' is supposed to return every tweet given that you are not running into rate limits. The former might happen as search only returns a partial set of tweets and Twitter does not specify which part or why it is partial [1].

Could you send me the _exact_ query you run in search.php as well as in track so that we can at least make sure that search does not return things that track should have provided? I.e. we'd start track for that query so that we have a least 9 days of tweets, and then do a _first_ search with the same keywords. If that provides different results than what is already in the database, then we'll have to investigate further.

[1] https://dev.twitter.com/rest/public/search explains that "the Search API is focused on relevance and not completeness. This means that some Tweets and users may be missing from search results. If you want to match for completeness you should consider using a Streaming API instead." 'track', aka 'filter', is one of those Streaming APIs and should return a complete set of results. Moreover, "The [search] index includes between 6-9 days of Tweets"

**Comment by dentoir** [comment]
Hi @psegovias 

I have nothing to add to @ErikBorra description of the scripts behaviour or the completeness of the search API results. Running search.php and track.php simultaneously is not something I've ever tried or TCAT was designed to do. I think you will run into a lot of problems, such as this: the track process buffers tweets before inserting, but because search.php may have already inserted some of those tweets in the buffer, the insert of the tweets from that buffer may fail, which means those tweets will get lost (and will be subsequently 'found' again by search.php). I guess this behaviour is simply not supported, and because of the buffer mechanism in track, which is intended for efficiency, a explicit existence check doesn't exist in that process as it does in search.php

How can change TCAT behaviour to always halt when queries are failing, by changing config.php and setting:

`define('DISABLE_INSERT_IGNORE', true);`

The log file should get more verbose now. Don't forget to turn this option off afterwards, though.

**Comment by eeftychiou** [comment]
I am experiencing the same, or at least a similar issue with @psegovias .
I believe the reason is because the search script is modifying tcat_query_bins_periods through a call to queryManagerSetPeriodsOnCreation at the completion of the script. As a result if the streaming tracker  for some reason stops and is restarted then it will skip those phrases because they have an end time. Therefore any keywords used in the search script will be skipped if the tracker is stopped and restarted unless the phrases are modified and a new period is started. 
I understand that this might not be a standard use case but if someone wants to capture as many tweets as possible with a history of say 6 days the search script might even take a whole day to complete and during that time no real time tweets are captured. So when the search script finishes and you start the track script , you have already missed a day's worth of tweets.
I am not sure if I explained things correctly and to be perfectly honest I do not understand the reason why the search script would modify tcat_query_bins_periods.

Sorry for opening up a close issue, but I do think this is a valid point to consider
