### ISSUE TITLE
Upgrading TCAT "local changes would be overwritten" error 

### ISSUE THREAD

**Issue by dormeir99o** [digitalmethodsinitiative/dmi-tcat#183]
Hi everyone!

During the upgrade, I get this message - 

 # git pull
Updating 4f587f1..75638ea
error: Your local changes to the following files would be overwritten by merge:
        analysis/index.php
        capture/index.php
        capture/stream/controller.php
        capture/stream/dmitcat_follow.php
        capture/stream/dmitcat_onepercent.php
        capture/stream/dmitcat_track.php
Please, commit your changes or stash them before you can merge.
Aborting

I've got a few questions, if I may:
Is the upgrade going to change these files? 
Should I let it overwritten the files? How should I do that?
Is the upgrade going to change anything in the database?

Thanks,

Dor

**Comment by theneva** [comment]
Hi!

> Is the upgrade going to change these files?

Yes. This is a Git thing, not a TCAT thing. It just means that you have made changes to the listed files on your own machine, and that these files have also been changed by the team here on GitHub.

> Should I let it overwritten the files? How should I do that?

Probably, but it depends—and you need to move your local changes out of the way first. To see what exactly you have changed locally, run `git diff HEAD`. After you've done that, run:

1. `git stash` to "move" your local changes to the Git stash; and
2. `git pull` to "upgrade" (pull down the latest TCAT changes from here on GitHub);

Now, if you want to keep the changes you've made locally, you can run `git stash pop` to move them back into the code. Of course, if you have changed the same lines of code in any of the files, you will have yourself a "conflict". They're pretty easy to resolve, though! And, if your local changes only include things like changing variable values, I'd say it's fairly unlikely.

If you do __not__ wish to keep your local changes, you have two choices:

- simply leave them in the Git stash (they do no harm there), or
- __IF YOU ARE ABSOLUTELY SURE__: `git stash drop` to remove the changes altogether. There is no going back from this, though: your local changes will be lost.

> Is the upgrade going to change anything in the database?

Pulling new code will not do anything to your database directly, but the code to interact with the database _may_ have changed. If you want to see what happens if you upgrade (assuming your Git remote is called "origin"), you can run:

1. `git fetch`
2. `git diff HEAD origin/master`

That should show you a list of all the things that will change.

Does that help?

**Comment by dormeir99o** [comment]
yes thank you - that helped very much!
another question -
Do you know if the upgrade contained any solution to the rate limit problem?

**Comment by theneva** [comment]
Awesome!

Not sure what you mean by 'the rate limit problem'. The rate limit is a Twitter thing: they restrict how much data (how many requests) you can obtain per set of API keys per... hour? 

So, no, upgrading TCAT won't do anything about hitting the rate limit. If you keep hitting the limit, you can supply more than one set of keys in config.php!

**Comment by ErikBorra** [comment]
Thanks @theneva for your great responses. Note that adding keys in config.php will only help for the REST API requests via search.php, timeline.php, etc.

If you are running into severe rate limits for tracking keywords, then you'll have to remove some high-volume queries, or live with the fact that you might not have all tweets for a particular set of keywords.
