### ISSUE TITLE
Link to tweet?

### ISSUE THREAD

**Issue by andersoloflarsson** [digitalmethodsinitiative/dmi-tcat#223]
Dear Developers,

I was wondering if it would be possible to add a column with "Tweet URL" to the "Export all tweets from selection" functionality - i.e. something like: 

"twitter.com/anyuser/status/541278904204668929"

Best,
Anders

**Comment by niczem** [comment]
You can simply use the tweet id, in an url like:
`twitter.com/user/status/{any tweet id}`
and it will forward you to the right url.

I think it makes sense not to add this to the export, because it would enlarge the exported files with data that can be super easy constructed with the data which is already in those exports.
