### ISSUE TITLE
Installer bug

### ISSUE THREAD

**Issue by bornakke** [digitalmethodsinitiative/dmi-tcat#225]
We are setting up an extra TCAT server (on ubuntu 14.04) but runs into the following error using the automated approach:

sudo ./tcat-install-linux.sh
Warning: no geographical search on Ubuntu 14.04 < 15.x
Continue install without geographical search [y/n]? y
tcat-install-linux.sh: cannot install: mysql-server already installed

Any ideas as to why this happens?

**Comment by ErikBorra** [comment]
Only from versions > 15 does Ubuntu include the mysql spatial extensions, which are required for geographical searches in the analysis interface.

**Comment by bornakke** [comment]
Hi Erik,

Please re-read my original post: I attempt to install without the spatial extension, but the installer fails anyway.

**Comment by ErikBorra** [comment]
Hi @bornakke,

could you please provide the full output from the installer?

Best,

Erik

**Comment by bornakke** [comment]
That is the full output. Or do you refere to some kind of log file?

**Comment by ErikBorra** [comment]
Ok, tnx. @dentoir @hoylen any ideas why the installer breaks when mysql is already installed?

**Comment by hoylen** [comment]
Because it **deliberately** checks to see if MySQL has been installed and exits (with that error message) if it finds it has been installed (line 413).

The installer expects to install MySQL itself. If there is an existing installation of MySQL, there would be no guarantees of how it has been installed, configured and secured. So the installer won't know how to work with it. Currently, the installer installs MySQL and sets up the root account's password: that is, has total control over it.

The alternative approach, which is what other things sometimes do, is to tell the user that it has partially installed it and then requires the user to manually create the databases, etc. to finish the job. But that makes it much harder for the user to install. That's the trade-off.

It is not just MySQL: I don't think DMI-TCAT has been designed to allow multiple instances of it to run on the same machine. So you can't really install "an extra TCAT server" on the same machine... actually, I'm surprised the earlier check in line 403 (detecting that TCAT has already been installed) did not trigger. In theory it can, but will require a lot of manual setting up -- if you really want to try this, you'll have to follow the manual installation instructions and modify them accordingly.

Your best approach is to install the second DMI-TCAT on another physical/virtual machine, with its own installation of MySQL.

**Comment by bornakke** [comment]
@hoylen Sorry for being imprecise in my first message. When I wrote that we are setting up a new tcat server I meant that we are setting up an entire new server and on this new machine we are installing TCAT (and one other tool).

So just to be sure of your message: The installer is only for installing TCAT on a completly empty machine on which e.g. LAMP haven't been installed yet?

**Comment by bornakke** [comment]
@hoylen Sorry for being imprecise in my first message. When I wrote that we are setting up a new tcat server I meant that we are setting up an entire new server and on this new machine we are installing TCAT (and one other tool).

So just to be sure of your message: The installer is only for installing TCAT on a completly empty machine on which e.g. LAMP haven't been installed yet?

**Comment by hoylen** [comment]
Yes, the installer will "`apt-get install`" MySQL server, MySQL client, Apache, PHP packages, etc.

If it is a brand new server, try uninstalling MySQL. Not sure if this is the best way, but try something like:

    sudo apt-get purge --auto-remove mysql-server

It is only the MySQL server that it deliberately checks for. Though to be really safe, it shouldn't proceed if Apache has already been installed. Right now the installer doesn't abort, but the result might not work if Apache has been configured in unexpected ways. Try removing the MySQL server and see if it works. In the future, consider using a "minimal" Ubuntu system.

**Comment by bornakke** [comment]
thank you :)

Since we will be running other software on the server I think I will go back to installing TCAT manually. Worked without problems earlier - just thought it would be interesting to try your new fancy script 👍
