### ISSUE TITLE
Recommended server?

### ISSUE THREAD

**Issue by johannessweater** [digitalmethodsinitiative/dmi-tcat#230]
I've been using the TCAT on an Amazon EC2 instance with Ubuntu 15.10 for the last month or so, and I think I need to upgrade my server. At present, it can take 15 minutes to load data in the analysis interface if I have over 600,000 tweets, and I've been experiencing a lot of server failures. The project I'm working on will likely require handling a couple million tweets at a time.

Can you tell me what specifications you recommend for the TCAT?

This is what I have currently:

Ubuntu 15.10 hvm:ebs-ssd
General Purpose, “Low to Moderate” network performance
t2.micro: Variable ECUs, 1 vCPUs, 2.5 GHz, Intel Xeon Family, 1 GiB memory, EBS only
(hey, it was on Amazon's free tier)

**Comment by fubespu** [comment]
Hi @johannessweater,

So far I'm thinking at the moment about the same question, I'll try to highlight my findings in this matter in the hope we can get something clear about it and figure out the best solution.

Unfortunately, ubuntu doesn't list a "compatible hardware" for the 15.10 version. But I don't think that the hardware for 14.04 or 16.04 would make any trouble. (http://www.ubuntu.com/certification/server/models/?vendors=HP) 

From my POV, getting a own server is the best option. Let's put it in figures:
- HP Proliant (SE316M1) : 2x Xeon Quad Core E5506 16GB DDR3 RAM B110i Raid (USED: http://www.ebay.com/itm/HP-ProLiant-SE316M1-DL160-G6-2x-Xeon-Quad-Core-E5506-16GB-DDR3-RAM-B110i-Raid-/142038778367?hash=item21122bc1ff:g:lY4AAOSwOyJX2rlU )
- 400 watt PSU running 24h: 9.6kWh, that would be about 1€ (€ x kWh = 0,11) per day, that would be close to 380 € per year (if running 365 days). 
- Total cost of first year: about 560 €. 

Since I'm using TCAT for electoral process research and other sporadic social phenomenas, It'll not be running 365 days... 

An other option is the Raspberry Pi, yes you heard right... At the moment I'm running a LAMP server (for WP, yes...) on Ubuntu server 32bits on this hardware and I must say it works flawlessly. The running costs of this hardware are more or less the same as a mobile phone charger...!!!. Before you ask, I didn't install TCAT on the Pi yet but, I'll do so this weekend. 

PD: Since TCAT needs for memory, I'll suggest more than 16GB of ram if running on dedicated servers.

**Comment by johannessweater** [comment]
Hi @fubespu,

I initially tried Ubuntu 14.04, but I wasn't able to access the GEO box option. And I don't believe the TCAT install script supports 16.04. But 15.10, which I accessed [here](https://cloud-images.ubuntu.com/locator/ec2/), has been working great for me, minus the aforementioned sluggishness above a certain tweet threshold. 

My research is also related to the electoral process, and therefore not year-round, so I'll probably stick with Amazon's virtual servers instead of investing in hardware myself. My main issue now is which Amazon instance type to go with. I understand that TCAT is designed with this kind of Amazon EC2 setup in mind, but I haven't been able to find any guidelines/suggestions for which instance type to go with.

**Comment by fubespu** [comment]
Hi @johannessweater ,

TCAT doesn't support 16.04 because the PHP7 thing, but the hardware which is supposed to work under 16.04 should also work fine with the 15.10 version. Yes, under 14.04 you won't have the GEO box option !. 

I'll be honest, just used Amazon EC2 once. What I can tell you is about the bandwidth used when tracking down hashtags that get Trending Topic very fast (such as elections). I managed to get a capture of the #Niza attacks the day they happend, I captured close to 1 million Tweets. With TCAT installed in my desktop PC (i7-5820k with 16GB DDR4 ram) under Ubuntu 15.10 64 bits the export of Gephi networks took very long with that amount of data. Doing some experiments with VirtualBox I found out that TCAT needs far more memory than CPU brute force. In my opinion you shouldn't get under 16GB wich takes you automatically to 4 vCPU. 

From your profile I deduced that you are keen in german elections (so am I), we should put our efforts together and have a little chat about that if you are interested. I'm native german speaker so language won't be a problem. 
PD: I'm doing this research for my pHd project.

**Comment by johannessweater** [comment]
Hi @fubespu,

Thank you, that's very useful. Also, I just found this related issue, which I somehow missed the first time:

https://github.com/digitalmethodsinitiative/dmi-tcat/issues/224

I'm afraid I'm not German -- I'm doing election research related to Scandinavia and the United States. But if you can put up with English, I think it could indeed be very helpful to compare notes.

**Comment by dentoir** [comment]
Hi @johannessweater 

That issue #224 is related to a CentOS specific problem which occurs also on high-end hardware. As @fubespu mentioned, capture of tweets is possible on really low-end hardware. I'm uncertain why you would get service interruptions if you would stick to purely capturing tweets. A 1 GB VPS is simply not enough to analyse larger datasets, it seems.

I've done quite some research comparing Amazon installations a while back. In my experience for analysis the fastest instances are the C4 types (compute optimized). You can get pretty decent performance with the smallest instance of C4. If you have large datasets however, disk access will quickly become the bottleneck and that's where Amazon gets to become really expensive. With Amazon, maximum throughput only increases when you get a bigger SSD storage.

Cheers,

Emile

**Comment by ErikBorra** [comment]
Thanks for the discussion guys. As it seems that there aren't any new suggestions or issues, I'm closing this issue. Feel free to reopen it.
