### ISSUE TITLE
Running the parse-csv.php script

### ISSUE THREAD

**Issue by johannessweater** [digitalmethodsinitiative/dmi-tcat#233]
Hey all --

Could someone explain how to run the parse-csv.php script? I keep getting this message:

PHP Warning:  include_once(/home/ubuntu/../../common/functions.php): failed to open stream: No such file or directory in /home/ubuntu/parse-csv.php on line 3
PHP Warning:  include_once(): Failed opening '/home/ubuntu/../../common/functions.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /home/ubuntu/parse-csv.php on line 3
PHP Fatal error:  Call to undefined function env_is_cli() in /home/ubuntu/parse-csv.php on line 5

**Comment by dentoir** [comment]
Hi @johannessweater 

Are you sure you have the latest version of TCAT? There was a path issue recently but it should've been fixed.

**Comment by johannessweater** [comment]
Hi @dentoir 

Turns out I was trying to run it from the wrong directory. But I'm now finding the parse script doesn't recognize csv files exported from the TCAT itself. I get this message: "Your input file was not recognized as a valid CSV file containing references to tweets. Sorry." ?

**Comment by arnoutponsioen** [comment]
I get the same error...

**Comment by ErikBorra** [comment]
Hi @johannessweater,

which csv files exported from TCAT are you referring to? If I export "Export tweet ids" from TCAT, I can easily import them to another installation using like this `cd /var/www/dmi-tcat/capture/ids; php lookup.php`.

**Comment by johannessweater** [comment]
Hi @ErikBorra,

Thanks for jumping in. No, the file I'm trying to parse is the "Export all tweets from selection" download.

**Comment by dentoir** [comment]
Hi @johannessweater 

Okay, that sounds silly, but is actually logical. The parse-csv.php script is intended for users who want to extract tweet IDs from CSV files where thet are referenced. Such IDs can only be extracted from recognized Twitter status URLs. As the TCAT export does not contain such URLs, the parse-csv.php script won't recognize Tweet IDs in it.

Curious: since you already have the IDs in the CSV file (column 1), why would you want to use the parse-csv.php script?

Issue #223 requests to add those URLs to the export; therefore I can close this issue, I think.

**Comment by johannessweater** [comment]
Hey @dentoir,

Thanks for the response. I've since been able to get around it by, as you said, going directly to the lookup script. It just requires a few more steps to pull the IDs out of the export and get it into the right format. Works great after that though!
