### ISSUE TITLE
Updating TCAT

### ISSUE THREAD

**Issue by jaruizso** [digitalmethodsinitiative/dmi-tcat#242]
Hi there,

I am tryng to update the platform. When I proceed to update, via automatic update a message shows:

"Your config.php file currently instructs us to upgrade everything with a complexity level up to 'trivial'. 
Please confirm you would like to schedule an upgrade of TCAT."

I click on accept, but nothing happens. Usually until know it worked, but I noticed that since this update (commit Drop additional distinct in select) nothing happens.

Any ideas?

Thanks in advance,
Javier

**Comment by dentoir** [comment]
Hi @jaruizso 

You do not get any confirmation message after clicking on accept? Could you check the following two things:

- Inspect your logs logs/controller.log file and show us the relevant (latest) content.
- Inspect the JavaScript console of your browser before and after you clicked on the link, to see if any JavaScript errors are triggered. All browsers support this feature, but it depends on the browser you use how to bring up the logs. You'll have to Google for this.

I'll need this data in order to investigate this problem.

Cheers,

Emile

**Comment by jaruizso** [comment]
Hi there,

Indeed, after clicking, I did not get any message. Its and issue with Safari, which has by default the execution of (some) javascript disabled. I tried with Chrome and worked as expected. After clicking I received the following message: "We are now running auto upgrade in the background. Please have patience or watch the logs/controller.log file on your server for progress indications."

You can close the issue.

Thanks for monitoring,
Javier
