### ISSUE TITLE
problem during DMI-TCAT TZ upgrade caused by missing LOCK TABLES access

### ISSUE THREAD

**Issue by brendam** [digitalmethodsinitiative/dmi-tcat#256]
I've had a problem while upgrading an old server (`git parse HEAD 19b9d56498a08a876176b6765719425d4b8fda89`) .

I've worked out now that it failed at line [762 of upgrade.php](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/3c72eed1c1a5403d74bd686507ed16173e06b015/common/upgrade.php#L762) the dump step - because the tcat mysql user didn't have LOCK TABLES access and couldn't do the dump. I made it worse by trying the upgrade a second time and then a third time after fixing the lock problem (giving the tcat mysql user LOCK TABLES access).

So now the tweets before the upgrade are 20 hours behind where they should be - which is the 2 x -10 hours from `CONVERT_TZ(created_at, 'Australia/Brisbane', 'UTC')` Brisbane doesn't have daylight savings, so I think  I can fix that by running :

```UPDATE binname_tweets SET created_at = DATE_SUB(created_at, INTERVAL 20 HOUR) where created_at < '2017-03-15 10:00:00'```

for each of the bins.

But I'm worried what other tables might then be wrong. Reading the upgrade script, it seems like `tcat_captured_phrases` is one that will also need fixing - could that also be fixed just by subtracting 20 hours?  But I'm not sure about the `tcat_error_ratelimit` and `tcat_error_gap` tables?

I have the `tcat_error_ratelimit_and_gap_1489573269.sql.gz` file, which was made after the first two timezone updates (on the final successful run)

2017-03-15 10:00:00 is before the new tweets with correct datetime start again - there is a 20 hour gap to pick a time inside.

thanks,

Brenda

**Comment by dentoir** [comment]
Hi @brendam,

Because the dump has failed, I think no operations have been done on tcat_captured_phrases, tcat_error_ratelimit and tcat_error_gap. Those operations would only have been performed if the dump succeeded. To fix the situation in principle, you could:

- make sure your user can now do the LOCK TABLES - and perhaps backup the three tables manually just to be sure
- manually comment out/edit upgrade.php to **only** execute the upgrade step after
line 756: // Start working on the gaps and ratelimit tables

The upgrade.php script should output a message like this during the run: "Dateformat fix found at ...'
If the date mentioned sounds sensible (i.e. it is a date on which you checkout out new TCAT code), then the upgrade of the three remaining tables should succeed.

Hope this helps,

Emile

**Comment by brendam** [comment]
@dentoir the third run had the LOCK TABLES permission & that dump succeeded, so it did do the tcat_captured_phrases, tcat_error_ratelimit and tcat_error_gap operations, but with the created_at in the tweets file set to 20 hours earlier than what it should be (GMT).

I'm trying to work out if fixing any copies of tweet created_at (like in tweets and tcat_captured_phrases) is enough to get everything accurate again, or if I need to fix/recalculate the tcat_error_gap and tcat_error_ratelimit tables. What are those tables used for - does it matter if they are not correct?

**Comment by dentoir** [comment]
The tcat_error_ratelimit and tcat_error_gap tables are not critical per se. They are used to export information about historic gaps in your capture and/or when a Twitter API ratelimit was exceeded. If you don't need to export this historical data, you could safely truncate those two tables.

As for the tcat_captured_phrases table matches tweet IDs to phrases. Currently it is only used for the exports mentioned above, but it will be used for more things in the future too, therefore it is good to reconstruct it.

I suggest the following steps:

- stop tcat
- backup the three tables, then truncate all three tables
- afterwards, run the upgrade.php script **only** from line 1262:
logit($logtarget, "Creating the tcat_captured_phrases table");
- this will rebuild the phrases table, and nothing else. the times should be in sync with the tweets table now
- start tcat

**Comment by brendam** [comment]
thanks, in the end I decided to do the fixes in MYSQL so I ran

```UPDATE xx_tweets SET created_at = DATE_ADD(created_at, INTERVAL 20 HOUR) where created_at < '2017-03-15 10:00:00';```
 
on each _tweets table and then

```UPDATE tcat_captured_phrases SET created_at = DATE_ADD(created_at, INTERVAL 20 HOUR) where created_at < '2017-03-15 10:00:00';``` 

to fix the phrases table - it showed the same 20 hour gap.

I truncated the `tcat_error_gap` and `tcat_ratelimit` tables.

The `upgrade.php` TZ update doesn't seem to update the hashtags or mentions or urls tables which also have `create_at` - is the created at field in these tables depreciated? Or am I just not reading the php correctly.

**Comment by dentoir** [comment]
You seem to be correct. Sigh. Just when I thought we had fixed this problem. These tables do indeed contain a created_at field, which is a copy of the original tweets value. The code to fix it (for the historical tweets where it was not okay due to time zone issues) is really straight forward; I've written most of it, and I can probably push that on Thursday. I think the philosophy behind these external tables was to reduce the amount of joins neccessary when implementing an analysis module. However, I'm not certain where and if they're actually used. After I've *removed* those fields completely in an experiment, the analysis panel and its frequency and export modules (also modules for 'mentions' specifically) continue to work. I will scan for them more thoroughly this week. If the fields are not referenced, we should consider either referencing them more so they will improve performance, or dropping them.

**Comment by dentoir** [comment]
I've added a fix for the issue on branches master and php7. This new upgrade step requires a bit of time, but is still reasonably fast.
