### ISSUE TITLE
Quoted status ID not collected

### ISSUE THREAD

**Issue by jaruizso** [digitalmethodsinitiative/dmi-tcat#257]
I have explored that in any of my datasets, quoted status is  not collected. For non of them. Its always blank. I run several DMI TCAT servers, but none of them collects anything in that column. Any ideas?

I tried to see whether this was fixed previously and I only found the link where quoted status was implemented, but nothing else: https://github.com/digitalmethodsinitiative/dmi-tcat/issues/144

**Comment by dentoir** [comment]
Hi @jaruizso,

You're right, thank you for the report. There was code missing; it has now been fixed in php7 and master. The quoted_status_id field seems to become filled with the tweet ID of links to other tweets made. I'm not sure if this field is only non-null whenever the tweet is commented upon, or it will be always there whenever another tweet is referenced, but I assume the latter. For historical tweets, you could therefore work-around to what is considered a 'quoted tweet' in the URLs table by running the URL expander on your bins and access the fully followed URLs referencing other tweets.

Cheers,

Emile
