### ISSUE TITLE
capture not working anymore

### ISSUE THREAD

**Issue by hliljegren** [digitalmethodsinitiative/dmi-tcat#258]
Today when I go to a the dmi-tcat/capture page I either get an empty page or a page with the message:

DMI-TCAT query manager
You currently have 5 query bins and are tracking 7 out of 400 possible phrases.

Sometimes I also see the "Your latest rate limit hit..." and sometimes not (so that part seams to be working) but then nothing more. So I can't administer any queries...

Any hints or suggestions are welcome.

**Comment by hliljegren** [comment]
Enabling errors and warnings in php gives me:

> Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/html/dmi-tcat/capture/common/functions.php:495 Stack trace: #0 /var/www/html/dmi-tcat/capture/common/functions.php(495): PDOStatement->execute() #1 /var/www/html/dmi-tcat/capture/index.php(133): import_mysql_timezone_data() #2 {main} thrown in /var/www/html/dmi-tcat/capture/common/functions.php on line 495

But if I go to dmi-tact/analysis everything is working as expected.

**Comment by oxygala** [comment]
I am having the exact same problem.

**Comment by dentoir** [comment]
Hi @hliljegren,

What operating system are you running? Did you recently do a git pull? Are you running on the master branch or php7? How long ago was your latest git pull? It appears your TCAT installation is failing to install time zone information into your MySQL database.

If you are root on your machine, the most immediate fix will likely be to follow the instructions below.

https://dev.mysql.com/doc/refman/5.7/en/mysql-tzinfo-to-sql.html

Otherwise, for a quick trial, could you try editing the capture/common/functions.php file and insert a new line directly above line 494:
$dbh = pdo_connect();

**Comment by hliljegren** [comment]
Hi @dentoir,

Updated dmi-tcat to latest version, no changes. Followed the instructions above to add time zone information, and now it works!

Thank you!

**Comment by dentoir** [comment]
Hi @hliljegren 

Good to know that worked. Just for our reference if someone else does encounter the same problem, you are not using Debian or Ubuntu Linux right?

**Comment by hliljegren** [comment]
No we are not! We are running CentOS Linux release 7.3.1611 with MariaDB 5.5.52

**Comment by alpita-masurkar** [comment]
I'm using TCAT on Ubuntu right now and am having a similar issue. I have a couple of query bins and the number of tweets that I have captured has not increased for a few days. What should I do?

**Comment by dentoir** [comment]
Hi @alpita-masurkar ,

Do you get to see a fully rendered capture panel? Are you running on the default branch (master)?

Could you check the log files and post any relevant messages:

- /var/www/dmi-tcat/logs/controller.log
- /var/www/dmi-tcat/logs/track.error.log
- /var/log/apache/error.log
(or some other location where PHP errors may show up)

Cheers,

Emile
