### ISSUE TITLE
Stupid question: how do i run again the Tcat?

### ISSUE THREAD

**Issue by uelramon** [digitalmethodsinitiative/dmi-tcat#266]
Hello guys,

how do i run tcat every time i restart my computer? Sorry for this dummy question...

**Comment by dentoir** [comment]
Hi @uelramon,

If you've installed using the auto installer, the recommended procedure, it should automatically start within a minute or so after bootup. If you've manually installed, you should configure [crontab](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Installation-Guide#install-crontab) as in the manual.

Cheers,

Emile

**Comment by uelramon** [comment]
Thanks @dentoir ,

I used the auto installer. As I do not have many programming skills, I have no idea what commands I should perform to start the program. In other software I use go through the commands to the folder where the software is installed and perform the command:

Bin / softwarename start

Would it be the same with Tcat?
Thanks again!!

**Comment by dentoir** [comment]
Hi @uelramon,

Do you have a server which is online permanently? Or are you running TCAT on your desktop/laptop computer? Because you've used the auto installer, TCAT should always start up, in both scenario's.

However, if you are running TCAT on your desktop, it will only capture tweets when your system is turned on, obviously.

**Comment by dentoir** [comment]
This is not a bug report
