### ISSUE TITLE
TCAT not loading 

### ISSUE THREAD

**Issue by mpaghi** [digitalmethodsinitiative/dmi-tcat#268]
It's been a couple of weeks since I'm not able to open the TCAT capture or analysis page. The capture page seems to make a 2-second effort to load but then stops with no result (page stays blank). On the other hand, the analysis page stays "loading" but never really directs me to the actual page. I don't understand why this started happening over night. Any solutions? I need to extract some data sets ASAP... help!

![tcat-capture](https://cloud.githubusercontent.com/assets/28696839/26041392/78d5924e-38fa-11e7-8df4-77954c38c8e4.JPG)

**Comment by dentoir** [comment]
Hi @mpaghi 

You'll need to provide more information than just a blank screen. Also, your attached screenshot does not show anything TCAT related.

Please attach fragements from all relevant log files, such as:
/var/log/apache2/error.log (or other location with Apache2 error logs)
/var/www/dmi-tcat/logs/controller.error.log
/var/www/dmi-tcat/logs/track.error.log

Did you recently do a `git pull`? Do you have auto updating enabled?

Best,

Emile

**Comment by mpaghi** [comment]
The attached file contains a fragment of each one of the error logs you mentioned above. 

Thanks,
-M

[TCAT Error logs.txt](https://github.com/digitalmethodsinitiative/dmi-tcat/files/1003002/TCAT.Error.logs.txt)

**Comment by mpaghi** [comment]
Hi, just wanted to do some follow-up on this issue. It is very important for me to find a solution since my current research is paused due to TCAT not working. 

Thank you,
-M

**Comment by brendam** [comment]
@mpaghi the Apache log fragment shows that your sql database has had a problem and one of the tables used by dmi-tcat is locked. You will need to use mysql recovery tools to repair the database so that dmi-tcat can access it again. You should backup the database before attempting the repair.

I'm not sure why the track error log is showing the stream stopped, but you have left your Twitter API credentials visible in it and should go and reset them so that they can't be used by someone else.

**Comment by ErikBorra** [comment]
Hi @mpaghi,

we have added some extra diagnostic tips to https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Bug-submission-guidelines#is-your-server-functioning-properly

Best,

Erik
