### ISSUE TITLE
Too long query bin name breaks database relations

### ISSUE THREAD

**Issue by xmacex** [digitalmethodsinitiative/dmi-tcat#280]
Hi. We recently had (and diagnosed and recovered thanks to @bacilo 's work, but didn't fix) an issue, where a long query bin name caused broken database relations.

For instance query bin named "NavCom2017_09_production_of_television_content" would lead to database table names with prefix`NavCom2017_09_production_of_television_content_`, while other tables would point to tables with prefix `NavCom2017_09_production_of_television_conten_` prefix (note the missing the final 't').

The symptom of this was truncated list of queries on the analysis UI (lexically up until the violating query bin), and *HTTP 500 Internal Server Error* on the capture UI
![HTTP 500](https://user-images.githubusercontent.com/879300/31441262-ea3d3e74-ae92-11e7-9c1b-d28cb9d518e9.png)

Suggested fix: query manager UI to disallow users from enter too long query bin names, or more generally query bin names which lead to invalid table names.

PS. is there a chance of SQL injection here, since user input goes into database structure? I guess there is some input validation, but it doesn't catch too long names.

Greetings from Copenhagen

**Comment by xmacex** [comment]
Maybe amend the `quoteIdent()` https://github.com/digitalmethodsinitiative/dmi-tcat/blob/3728484d88088a400f6f9eeddcbaed0984606acd/capture/common/functions.php#L106 , but just truncating is going to create unambiguous table names if identifying characters are only at the end of the query name. Maybe just harass the user about too long names and ask them to choose a different name?

**Comment by dentoir** [comment]
Thanks for reporting this issue. I think informing the user is the best approach in this case. They'll be able to think of a more succinct bin name themselves. Feel free to issue pull requests, otherwise I hope to look at it shortly. The quotes are in backticks, which should prevent an injection in this case. The 64 character limit appears to be a MySQL internal limit. De PDO library only allows placeholders for the field data.

**Comment by dentoir** [comment]
Thanks, I've merged this commit to php7 as well and added an additional check for bin name length with the CLI script (such as search.php).

**Comment by xmacex** [comment]
Thank you @dentoir!

Contemplating on this, I find it a little surprising that MySQL throws error *1059 Identifier name too long* when trying to create table with a long name right in SQL, but in this case with TCAT and PDO, it is passed through 🤔. Maybe a database configuration matter? I apologize I wasn't close to the action when it happened to us, but our database exploded pretty badly. Also note the limit of 45 I introduced is arbitrary and static. I chose the longest that didn't break for us, although MySQL limit (64) minus longest table name suffix in the `capture/common/functions.php` `CREATE` statements "_hashtags" (9) would yield a different limit (55).

**Comment by dentoir** [comment]
Hi @xmacex 

The 45 character limit sounds fine with me; it should be enough to define your dataset.

I've done a quick test from the command-line (CLI script search.php, using the codebase before the patch) and my TCAT instance actually refused to create the long bin, and threw a 1103 Incorrect table name exception instead. So this appears to be at least somewhat implementation/version specific. For reference I'm using Debian Stretch with PHP 7 and MariaDB 10.1. In any case, because the patch only works on new bins, it won't break anything.
