### ISSUE TITLE
TCAT cannot store the new ≤ 280 character tweets

### ISSUE THREAD

**Issue by xmacex** [digitalmethodsinitiative/dmi-tcat#283]
A historical moment is taking place in November 2018, and [Twitter is increasing the maximum tweet length from 140 to 280 characters](https://twitter.com/Twitter/status/928004549478047744). [TCAT database schema](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/09bd3dde6802bd9d8f3cea1c0a79c71322441d5e/capture/common/functions.php#L217) has the tweet content as `VARCHAR(255) NOT NULL`, and 255 < 280 will lead to storage failures.

There might be other places where this should be an issue. Exporting should be checked at least, but I'm just flagging it here for now. To be investigated.

**Comment by xmacex** [comment]
Hmm there's [`full_text`](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/09bd3dde6802bd9d8f3cea1c0a79c71322441d5e/capture/common/functions.php#L1374), what is that for?

**Comment by xmacex** [comment]
Related #228

**Comment by dentoir** [comment]
There's no way around it. We'll have to alter the table structure, which is trivial for new bins. Upgrading the existing bins will be more painful when they are large, because of the index rebuilding. We can make upgrading optional per bin, as it is for some other upgrade steps. If you have a multi-million tweet bin, you could always consider starting a new bin with a different name and the same queries.

What should the new VARCHAR size be? The VARCHAR size is tricky. I think we need to count with the theoretical usage of 4 storage characters per visual character (because of utf8mb4 character set). That would mean we would need a VARCHAR size of 1120.

**Comment by ErikBorra** [comment]
Suggestion: let the upgrade script automatically upgrade bins with <= 200.000 tweets. For larger bins, let the upgrade script stop capture and make a new bin with the same params as the old bin, but now with more space for tweets. Thumbs up or down?

**Comment by ErikBorra** [comment]
Alternatively we could just start replicate the params of each old bin in a new bin with longer tweets, and then copy all old info in the new bin in the background, and delete the old bin when done.

**Comment by brendam** [comment]
What is happening for this? Is it something I can help with?

**Comment by ErikBorra** [comment]
Hi @brendam, 

thanks for your message. 

Existing bins currently truncate long tweets. We thus will patch the 'create bin' code, so that new bins will capture long tweets too. Users who want to be able to capture long tweets can stop their old bin and create a new bin with the same parameters.

Furthermore, we consider writing an upgrade script that makes new bins based on old parameters (but with the patched create bin code), starts those new bins, and then stops existing bins. Then, in the background, old tweets can be copied into the new bins without creating long gaps due to table locks of ALTER TABLE queries.

Currently the tweet column has type VARCHAR. We are experimenting with other types too (e.g. TEXT) and possibly faster indexing (BTREE, full text, ...) and search (MATCH AGAINST instead of LIKE). 

What are your thoughts on this?

Best,

Erik

**Comment by brendam** [comment]
I’m not sure, I’d probably stick to VARCHAR given that it still is a fixed length (although does need to cope with UTF8 multibyte chars). We are tracking the QLD election now, so I’d like to use the new bin idea soon - do you have a branch for this yet? It’s night here now, so I won’t be working on it until tomorrow.

**Comment by brendam** [comment]
As well as making the tweet text field larger, when the tweet is longer the tweet text will be in the `extended_tweet` dictionary object, `full_text` field, and the truncated version in the `text` field. The `extended_tweet` dictionary object also has the longer version of `entities` and so the capture code should probably get them from that field instead of the short `entities` field (which only has the entities from the truncated `text` of the tweet)?

https://developer.twitter.com/en/docs/tweets/tweet-updates#chars280

**Comment by dentoir** [comment]
Hi,

I'm running some benchmarks on the effects in terms of disk space and query performance of changing the DB text field to type TEXT. So far this looks promising. I'll send an update today. We can add 280 characters support for new bins very shortly; and then look at the best update procedure.

**Comment by dentoir** [comment]
Hi,

The 280characters branch is a branch with a small patch which uses a TEXT column instead of a VARCHAR type for text in the tweets tables, on bin creation. It also removes the 'truncated' attribute for new bins, as this is a deprecated field. I've benchmark this in terms of disk space and performance. Performance should be slightly better for the modules, unchanged for the analysis panel and disk space per bin should increase by ~1 %. I've noticed we're not using FULLTEXT indexes as optimally as we should but that's for later.

I'm now testing this on one of our own servers. Feel free to try it out. It's based on the php7 branch which has now merged with master. Once we know this doesn't break anything, we can merge this probably tomorrow.

Now, obviously, you'll want to upgrade _existing_ bins to support the new character limit. I've been discussing a strategy which minimizes lock times, but that patch may not be ready tomorrow. It is a really simple MySQL one liner:

`ALTER TABLE some_bin_name_tweets MODIFY text TEXT;`

This becomes only problematic if your bin is very large, if you have many bins and if you want minimal downtime. Feel free to experiment with upgrading ahead of our patch. We'll detect on-the-fly if tables have been altered already. Small disclaimer: though I'm reasonably sure this is the route we'll take, if you are more the conservative type, you should wait for the patch to be merged.

Best,

Emile

**Comment by dentoir** [comment]
Hi,

We've added an upgrade step to modify existing bins to allow them to store 280 character tweets. Use the common/upgrade.php command-line script (as usual) for this and follow the instructions. The script is purposed to reconstruct the tables in the background, without any interruption in the capture. It is the first time we try a new trick: rebuild the bin as a separate table prefixed with tu_, afterwards quickly drop the existing table and rename the reconstructed table to the proper name. I'm running the upgrade script now on several of our own servers. If all is well, we will merge this branch into master next Monday. For the record, the text field in the _tweets table will henceforth be TEXT.
