### ISSUE TITLE
Change database

### ISSUE THREAD

**Issue by ghost** [digitalmethodsinitiative/dmi-tcat#292]
Hi, I changed the database in which TCAT registers the tweets, I prefer having my datas on another server. So, works fine for a user timeline or for a past search, but when I want to track a phrase from now, it does not work... Have you any idea why ?

Thank you for your help, and thank you for this beautiful tool.

**Comment by ErikBorra** [comment]
Hi @edouards57 ,

could you please be a bit more specific. Do you have any code/config diffs we may look at?

Best,

Erik

**Comment by edouards57** [comment]
I just modified the settings of the database in _config.php_ :
`$dbuser = "tcatdbuser";`
`$dbpass = "PaSsWoRd";`
`$database = "twittercapture";`
`$hostname = "New.IP";`

It works fine when I call for the 3200 lasts tweets of a user id, or when I call for some tweets of the 10 last days about a topic.
But when I want to use the capture window to follow a topic in real time, it does not work anymore...

**Comment by ErikBorra** [comment]
In order to set up a socket connection to the stream API, you either need to use an IP address on the same machine, or set up a socat tunnel to the other machine.

I think a quick fix for you is to overwrite the hostname variable in [capture/common/functions.php](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/common/functions.php#L2359)

Just add `$hostname = 'localhost'` on line 2360, i.e. after the global variable is included.

Hope this helps,

Erik
