### ISSUE TITLE
Database upgrade

### ISSUE THREAD

**Issue by limogin** [digitalmethodsinitiative/dmi-tcat#326]
When upgrade database from a new dmi-tcat release, I see messages as this:

`Updated 82 tweets in .. `

I see each two or five minutes aproximately from a query bin where there are 10 million tweets saved.
I understand that the process will then take several years to update. It's not a reasonable thing to do. 
I've had the installation up and running for over a year and I haven't had this problem until now. 
What's is the problem?

**Comment by dentoir** [comment]
Well it will take a very long time, though not several years. The iteration is only over those tweets which should be updated, so all the numbers (82, ... etc) will not add up to 10 million. Very difficult to give an estimate how much time it takes, but I've updated many multi-million tweet bins. The problem is updating rows in a huge table takes a long time in MySQL, so run time grows non-linear with big datasets. An alternative route is to make a fresh, separate lookup bin where you'd simply do a REST lookup on all the tweet IDs in your existing bin (using `lookup.php`). I think you'll be able to retrieve ~500k tweets per 24 hour or so, but I'm not sure.

**Comment by limogin** [comment]
Unerstood. But there are times when we can't wait long enough for the database to update because we need to keep getting data. But If I do a lookup I leave blank the idfile var if the data is already in the database?

```
/capture/ids/lookup.php 

$bin_name = '';            // name of the bin
$idfile = '';              // path to the input file name. the file must contain only a tweet ID on every line
$type = 'lookup';          // specify 'lookup
```

**Comment by limogin** [comment]
To today, the upgrade process takes 2 months and is not yet complete. This is a very long time that prevents us from continuing to incorporate information. It should be possible to do it in a more efficient way.

**Comment by dentoir** [comment]
Yes there is, dump all tweet IDs using MySQL and rebuild the bin using the lookup.php script - which I believe captures 20.000 tweets per second. Capture should, on fast machines, continue with the upgrade in progress though.

**Comment by limogin** [comment]
I'm not sure it's an adequate solution either. At speed of 20.000 tweets per hour it would take 4 years to  complete whe whole process. It's unreasonable. For practical purposes I have the installation inoperative. 

Can I stop the process and use the application?

**Comment by dentoir** [comment]
Hi @limogin 

Register the current table the upgrade is working on (simply from the log messages) first, stop the MySQL upgrade script, afterwards run an `OPTIMIZE TABLE` for all tables related to that bin `_tweets`, `_media` etc. The bin will work without the OPTIMIZE TABLE, but will not utilize indexes and be very slow. Other tables will not need to be optimized.

**Comment by limogin** [comment]
I will made that, but from July the update process is still not over.

**Comment by dentoir** [comment]
Slow database upgrades has been addressed for new TACT installation or after manually upgrading to TokuDB (issue #348)
