### ISSUE TITLE
Matching retweets dropped in streaming collection

### ISSUE THREAD

**Issue by SamHames** [digitalmethodsinitiative/dmi-tcat#329]
I think there's an issue with TCAT failing to retrieve the full tweet text of retweets on streaming collection, causing retweets that otherwise match a query to be dropped. If I'm understanding correctly this will affect all streaming API collection using keywords since the longer character limits were introduced at the end of 2017.

Background:
I was trying to investigate why I was seeing a substantial drop (nearly 50%) in collected tweets on a long running keyword streaming collection:

```
Tweets collected   Month
657361    2017-06-01T00:00:00
696060    2017-07-01T00:00:00
965170    2017-08-01T00:00:00
775381    2017-09-01T00:00:00
814809    2017-10-01T00:00:00
969831    2017-11-01T00:00:00
718044    2017-12-01T00:00:00
395285    2018-01-01T00:00:00
458764    2018-02-01T00:00:00
376308    2018-03-01T00:00:00
312504    2018-04-01T00:00:00
314859    2018-05-01T00:00:00
325003    2018-06-01T00:00:00
363800    2018-07-01T00:00:00
108973    2018-08-01T00:00:00
```

I think the problem is that for streaming collections the check on [line 1660](
https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/common/functions.php#L1660) is incomplete, because the streaming endpoints always operate in the extended_tweet compatibility mode and never provide a full_text field. The check there on the retweeted status should be similar to [line 1633](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/capture/common/functions.php#L1633) to retrieve the full retweet text, not just the truncated text.

I'm hoping there's something obvious I'm missing, as far as I know this instance has been tracking development fairly closely and is upgraded regularly.

**Comment by SamHames** [comment]
I should also add that this means that the text of retweets is still being truncated on streaming collections.

**Comment by dentoir** [comment]
Hi @SamHames 

Thanks for the report. Obviously something to fix in short time. Unfortunately I'm not working at the moment and though a fix appears to be straightforward, it does need proper testing (issue #311 was in such a testing branch but this issue didn't get noticed).
I agree the logic from line 1633 could probably be safely re-used. If you, or anyone else has time, please issue a pull request and I can put it in a test branch and test it on one of or own servers as well. Otherwise I can't promise this will be fixed within a week.

**Comment by SamHames** [comment]
I may be able to submit a fix, but I'm on holiday as of tomorrow so not likely to be in the next week.

I've done some more testing against tweet counts collected through a different tool, and it looks like the scale of the problem is quite significant. This is the comparison of counts for the auspol hashtag over a recent period (Australian politics, high activity and lots of shared content). The TCAT bin emulation counts use the same logic as TCAT currently uses for bin assignment, on the corrected full text and truncated retweet text respectively.
![auspol_validation](https://user-images.githubusercontent.com/8400977/44434087-ae4dcf80-a5ec-11e8-8637-17850f55fa33.png)

I think this means that for keyword based streaming collection, tweet volume measures that include retweets will not be reliable since the introduction of the extended tweets in November 2017.

**Comment by dentoir** [comment]
Hi,

The https://github.com/digitalmethodsinitiative/dmi-tcat/tree/issue329 branch provides a fix for this issue which is hopefully complete. I'm performing a wider test now and any test feedback is welcome.

**Comment by pingupingu** [comment]
@dentoir Thank you for the fix, I am testing it at the moment.

**Comment by pingupingu** [comment]
@dentoir On a 'track' instance with heavy RT and varying tweet lengths, with the fix we are capturing 2-3x more tweets. On a 'follow' instance, I don't see any variation.

**Comment by dentoir** [comment]
Hi @pingupingu 

I've been testing the patch on a follow instance, but did notice an increase in the nr. of tweets captured. Are you sure you've restarted your follow bin (by sending the process a TERM signal, this does not happen automatically yet).

Because follow bins tend to grow slowly, I've added a temporary test script to the issue 329 branch which calculates overall average lengths and nr of tweets for two user-defined periods (i.e. before and after applying the patch!). It can be found in the helpers directory. If you'd like, you could run this test script on your follow server to verify the patch results.

`https://github.com/digitalmethodsinitiative/dmi-tcat/blob/issue329/helpers/tempory_test_issue329.php`

Best,

Emile
