### ISSUE TITLE
what will be the easiest way to disable certain features for certain users?

### ISSUE THREAD

**Issue by zhanglipku** [digitalmethodsinitiative/dmi-tcat#338]
I want to disable the "export tweets" feature for some users currently on my TCAT, but don't want to jeopardize the integrity and stability of TCAT, how should I do that? Or is it something the developers would consider?

**Comment by dentoir** [comment]
A quite delayed reply, but fine-grained ACLs (which exists as a feature request) would never tackle the resource issue, because high load on the database can be caused by a wide variety of selection / export / analysis etc. queries. TCAT has a traffic light feature, which can be enabled in `config.php` and allows the admin to set a maximum number of simultaneous analytical operations.
