### ISSUE TITLE
Upgrade database engine from MyIsam to modern replacement.

### ISSUE THREAD

**Issue by marciofoz** [digitalmethodsinitiative/dmi-tcat#348]
Hi !!

Based on the fact that the MyIsam engine is not available for new DBMS, why not migrate to the InnoDB engine? I believe that if all tables are using the InnoDB engine and have a primary key, we can start using DMI-TCAT on Mysql clusters as well.

Thank you.

**Comment by bosim** [comment]
I am curious to know as well. I believe there are several performance penalties when using MyISAM, especially I found the query ```SELECT count(t.id) AS notweets, MAX(t.created_at) AS max  FROM <bin>_tweets t``` is benefiting from the ```created_at``` index, making it over twice as fast when using InnoDB.

**Comment by dentoir** [comment]
Hi @marciofoz 

Historically, InnoDB did not support `autoincrement` fields, which it does now. Switching to InnoDB will certainly decrease crash-recovery times, though I'm not so sure about the performance aspects (did an experiment about two years ago on an Amazon instance and it actually degraded sequential read speeds, but this was on a clean, optimized MyISAM table). 

InnoDB is much faster with UPDATES, which TCAT performs in its URL expander and during upgrades (which can take a looong time).

Anyway, we're forced to switch regardless, so we might as well start with a InnoDB branch. I suggest switching on InnoDB in the default installation, but leave upgrading to the end-user.

**Comment by dentoir** [comment]
I'd love to hear people thoughts on using MonetDB as database backend instead. It would require a much larger overhaul to implement but I'm reading it could be a massive performance boost and it still is SQL.

**Comment by dentoir** [comment]
Update on this. I narrowed down the investigation to either use the MySQL MyRocks or TokuDB storage engines from Percona, as these are both available on modern mainstream MariaDB servers, then went with TokuDB. TokuDB is more mature and widely used in bigdata companies. I've been testing a experimental branch called [tokudb](https://github.com/digitalmethodsinitiative/dmi-tcat/tree/tokudb) with success. Querying is clearly faster and diskspace is also clearly lower. I'm using LZMA compression by default. Additional attractive features (though not yet concretely tested in TCAT context) are:

- faster `UPDATE` statements
- low-crash recovery times, even lower than InnoDB
- indexing operations should no longer block the capture (yeah!)

I will also check whether making a backup of a bin still blocks the capture or not, as it does with MyISAM.

True technical difficulties were few, most notably:

1. We have to use regular TEXT indexes instead of FULLTEXT (which shouldn't decrease performance because FULLTEXT was never used due to stopword issues).
2. We need to install the TokuDB plugin and disable Linux kernel Transparant HugePage support (which *does* require changing the boot parameters - see install script)

**ATTENTION** only tested on Debian 9.0 stable (stretch) for the moment.

What does the new branch do?

- tcat-install-linux.sh -B tokudb should install TCAT with tokudb as the default engine (**tested only on DEBIAN**)
- import.php somebin.sql.gz should automatically import a previous MyISAM-based export into a TokuDB-based installation
- convert-myisam-to-tokudb.php produces SQL statements which you could execute at your own risk to convert bins into TokuDB in-place
- tracking and analysis should continue to work as expected (_test!_)

What's next?

- further testing!
- add Ubuntu support

**Comment by marciofoz** [comment]
Hi !

From Percona [site](https://www.percona.com/doc/percona-server/LATEST/tokudb/tokudb_intro.html): 

> Availability: | TokuDB is deprecated in the 8.0 series and will be supported through the 8.0 series until further notice. This storage engine will not be included in the next major release of Percona Server for MySQL. We recommend MyRocks as a long-term migration path.

**Comment by dentoir** [comment]
I kind of went with this statement from last November:

https://www.percona.com/blog/2016/11/01/future-tokudb-percona/

I'm quite happy with what I have seen thus far from TokuDB, but I can run an experiment with MyRocks as well.

**Comment by dentoir** [comment]
The thing with MyRocks is that we may need to actually switch database server (to either the Facebook MySQL server or the Percona MySQL server), or use the beta version of the storage engine inside the latest MariaDB. That may seem like a not-so-big-thing if we accept this feature will be available on fresh installs only, but I'll have to check whether those database servers provide the GEO function TCAT uses etc. (which the probably do..)

**Comment by dentoir** [comment]
Modern database engines now supported in new TCAT installations.
