### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by jsegoviamartin** [digitalmethodsinitiative/dmi-tcat#431]
Hi!
Any chance of running the installation scripts on Ubuntu 20.04?
Cheers,
j

**Comment by ErikBorra** [comment]
Should run fine!

**Comment by jsegoviamartin** [comment]
I am getting this: 

tcat-install-linux.sh: error: unsupported distribution: Ubuntu 20.04

any idea why?
j

**Comment by ErikBorra** [comment]
Because of this line: https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/helpers/tcat-install-linux.sh#L350

You can either use ubuntu 18.04, install tcat and then do an apt-get upgrade, or change the line to 20.04 and hope for the best :) In the next few weeks we unfortunately do not have time to test this install script on newer Ubuntu versions. Will make sure this test is one of the highest priorities though.

**Comment by alexandreteles** [comment]
> Because of this line: https://github.com/digitalmethodsinitiative/dmi-tcat/blob/master/helpers/tcat-install-linux.sh#L350
> 
> You can either use ubuntu 18.04, install tcat and then do an apt-get upgrade, or change the line to 20.04 and hope for the best :) In the next few weeks we unfortunately do not have time to test this install script on newer Ubuntu versions. Will make sure this test is one of the highest priorities though.

As far as I can tell there is no major differences on 20.04 that would break the installation script. In fact, I'm running my instance on 20.04 and it was deployed using this exact script by just changing the expected Ubuntu version. Does the CI runs deployment tests? If so, creating a new test by just bumping the OS version might be a quick way to test this to at least give a "not fully tested, but go ahead" for people looking into running TCAT on Focal.

**Comment by dale-wahl** [comment]
Tested Linux 20.04 and found no issues. Install script has been updated in pull request #436.
