### ISSUE TITLE
Export\import problem

### ISSUE THREAD

**Issue by Alotsi** [digitalmethodsinitiative/dmi-tcat#438]
Hi guys,
After running out of server space on my tcat installation, I've used the built-in commands for exporting and then importing the bins to a new installation. On the new installation the numbers from the interface look ok, but the data takes significantly less space on the server than on the old server (approx. by a third). 
The import went without errors, however the export had one error: 
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilige(s) for this operation' when trying to dump tablespaces
Could it be that not all the data was in fact exported? Is there a way to check that the export\import process contained all the data?
Both servers run Ubuntu 18.04 (LTS) x64 PHP 7.2
Thanks!

**Comment by dale-wahl** [comment]
Our resident TCAT expert is away for the moment, but I believe the short answer is no. You can export summary information by bin and compare it between the old installation and the new to verify or otherwise come up with a comparison script that could potentially be quite unwieldy.

We looking for ways to better archive and backup data, but our current solution is to store the bins as they are on slow storage.

As to your specific error, I found this stack exchange on the issue: https://dba.stackexchange.com/questions/271981/access-denied-you-need-at-least-one-of-the-process-privileges-for-this-ope

It looks like you may be able to resolve it by `GRANT PROCESS ON *.* TO someuser@localhost;` while connected to your sql database. "someuser" being your dbuser from the config.php file. Let us know if that is at all helpful!

**Comment by dale-wahl** [comment]
I found [this response on StackOverflow](https://dba.stackexchange.com/a/274460) in regards to your `mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilige(s) for this operation' when trying to dump tablespaces` error. You are running into that issue because you do not have sufficient privileges with the user. That implies the database user in your TCAT configuration file, `config.php` was not set up with all privileges. `GRANT ALL PRIVILEGES ON thenameofyourtcatdatabase.* TO thenameofyourtcatuser;` or something similar should fix that error.

That being said, the export script is not complete as is. It contains all the actual tweets collected and information around them but is missing some metadata (such as the recorded gaps and rate limits). We are working on [an archive script](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/archive_dev/helpers/archive_export.php) that will more fully export (and delete) everything from an existing TCAT instance. You can learn more about [that progress here](https://github.com/digitalmethodsinitiative/dmi-tcat/issues/444).

**Comment by dale-wahl** [comment]
The [archive script](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/archive_dev/helpers/archive_export.php) much more comprehensively exports data. Unlike the `export` script, it also collects relevant (by bin) metadata and error data.
