### ISSUE TITLE
Installation on MacBook Pro M1

### ISSUE THREAD

**Issue by Alberto230398** [digitalmethodsinitiative/dmi-tcat#443]
**Describe the bug**
Good morning, I'm trying to install TCAT on a MacBook Pro M1 using UTM virtual machine with Ubuntu 20.04, but I'm unable to install the tool.
**To Reproduce**
1. Install TCAT via shell

**Screenshots**
If applicable, add screenshots to help explain
<img width="522" alt="Schermata 2021-11-03 alle 18 07 13" src="https://user-images.githubusercontent.com/71700140/140979893-58390cb0-0fa9-4b0e-96a1-db6eabf45e38.png">
 your problem.

**Environment:**
 - OS (Ubuntu 20.04 on MacBook Pro M1 [OS X 11.4])

**Comment by dale-wahl** [comment]
Buon giorno Alberto,

My Italian is pretty rusty, but it looks like the install software is unable to find the Maria database. The `tcat-install-linux.sh` script has been tested to work with Ubuntu 20.04 (though not on a virtual machine running on a Mac).   

I would recommend installing TCAT with Docker. It containerizes the entire TCAT environment so it can be easier to isolate issues and avoid conflicts. Install Docker however your system requires ([you can install directly on your MacOS without the Ubuntu virtual machine (recommended)](https://docs.docker.com/desktop/mac/install/) or [install Docker on the Ubuntu virtual machine](https://docs.docker.com/engine/install/ubuntu/)) and follow our instructions here: https://github.com/digitalmethodsinitiative/dmi-tcat#docker

You could also try to install TCAT manually and either try to resolve your database installation issue by installing tokudb in a different fashion (https://mariadb.com/kb/en/installing-tokudb/) or [use a different database](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Installation-Guide/#the-tokudb-storage-engine). Full manual instructions are here: https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Installation-Guide/#manual-installation

Please include the commands you run so we can try to determine where exactly it's failing. In your case, perhaps copying the text instead of screenshots may help for Google translating purposes! :grin: Let me know how either of those installations go and if you have any other issues.

In bocca al lupo!
