### ISSUE TITLE
Installing problem: The apache2 configtest failed.

### ISSUE THREAD

**Issue by baiyuan523** [digitalmethodsinitiative/dmi-tcat#450]
**Describe the bug**
After running sudo ./tcat-install-linux.sh command on Ubuntu, it shows 'The apache2 configtest failed' 'ServerName takes one argument, The hostname and port of the server ','Action 'configtest' failed'. When running this command again, it shows 'tcat-install-linux.sh: cannot install: TCAT already installed: /var/www/dmi-tcat'

**Screenshots**
<img width="512" alt="微信图片_20220228135304" src="https://user-images.githubusercontent.com/100407057/155931460-4413b522-dbb3-4fe1-aafb-e040107e5e00.png">

**Environment:**
 - Windows, Ubuntu 20.04.4

**Comment by dale-wahl** [comment]
Hello again Baiyuan523. Sorry you are having more difficulties. Did you edit the `tcat-install-linux.sh` to contain a `SERVERNAME` [here](https://github.com/digitalmethodsinitiative/dmi-tcat/blob/481dfcf681d8ed8712f638798f499a820bb6f882/helpers/tcat-install-linux.sh#L43)? If not, the setup tries to guess your IP address and make that the servername.

Your problem appears to be with apache. You can check the tcat.conf file and see what it says your SERVERNAME is. `cat /etc/apache2/sites-enabled/tcat.conf` ought to let you read the file and you should be able to see what the SERVERNAME is. It ought to be your IP address, if you did not set it to something else during the installation/change the install file. If you are using it just for your own use, you could probably change it to `localhost` and access it via your browser.

**Comment by baiyuan523** [comment]
Hi Dale! Yes, I do need some extra help in IT related stuff ;(
With the command you provided, I do notice there's a problem with my ServerName. So how can I add my IPv4 address on it and make the code ran to the next step? I haven't created a password yet...

Thank you very much!










------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dale ***@***.***&gt;; 
发送时间: 2022年2月28日(星期一) 下午5:43
收件人: ***@***.***&gt;; 
抄送: "Boyuan ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [digitalmethodsinitiative/dmi-tcat] Installing problem: The apache2 configtest failed. (Issue #450)





 
Hello again Baiyuan523. Sorry you are having more difficulties. Did you edit the tcat-install-linux.sh to contain a SERVERNAME here? If not, the setup tries to guess your IP address and make that the servername.
 
Your problem appears to be with apache. You can check the tcat.conf file and see what it says your SERVERNAME is. cat /etc/apache2/sites-enabled/tcat.conf ought to let you read the file and you should be able to see what the SERVERNAME is. It ought to be your IP address, if you did not set it to something else during the installation/change the install file. If you are using it just for your own use, you could probably change it to localhost and access it via your browser.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dale-wahl** [comment]
You could attempt to edit the `/etc/apache2/sites-enabled/tcat.conf` file itself with replacing whatever you have with your IP address or localhost. Since the installation seems to have run, that may be sufficient. Though if it was successful, it should have provided you with your username and login. 

I recommend using the [Docker installation instructions](https://github.com/digitalmethodsinitiative/dmi-tcat#docker). They are the easiest to use as well as fix when things go wrong. You should be able to follow those instructions and have TCAT up and running.

Fixing your current install is a bit trickier. You can try to fix it by running through the [manual installation guide here](https://github.com/digitalmethodsinitiative/dmi-tcat/wiki/Installation-Guide/#manual-installation). To re-run the helper script, you wouldl need to remove TCAT completely (or at least everything that the script checks for) and then re-run it. There are _[some rough instructions here](https://github.com/digitalmethodsinitiative/dmi-tcat/issues/162)_. I believe you might run into an issue with `mysql` and have to remove that as well. But that's a guess. For our purposes, we generally install on a new machine so I would just whip it and start from fresh... So I would again recommend using the Docker installation guide! If that fails, you can very easily remove the containers and start again!

**Comment by dale-wahl** [comment]
Set default Docker SERVERNAME here: https://github.com/digitalmethodsinitiative/dmi-tcat/commit/22d980ded27fe27503e08f520c56ac97aba9cfc1

Let us know if you need additional help.
