### ISSUE TITLE
Remaining Request Stuck

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#456]
Hello! im using search capture, and after a couples time, the "remaining requests" stuck at 180 and now i get the error 88, any idea why this happen? is the first time btw.

`{"errors":[{"message":"Rate limit exceeded","code":88}]}
`

`2022-08-24 15:01:00	key: 0	remaining requests:180
....................................................................................................
max id: 1562505883275653120
....................................................................................................
max id: 1562505033232441345
....................................................................................................
max id: 1562503837537013761
....................................................................................................
max id: 1562502804824276992
....................................................................................................
max id: 1562501795036872704
....................................................................................................
max id: 1562500880288858112
....................................................................................................
max id: 1562499636752830465
....................................................................................................
max id: 1562498178938593282
....................................................................................................
max id: 1562497052822880256
....................................................................................................
max id: 1562495644052230146
2022-08-24 15:01:54	key: 0	remaining requests:180
`

**Comment by ErikBorra** [comment]
Hi @psegovias,

The error message indicates that you are getting rate limited.

https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets specifies that you can get 180 requests per 15 minutes. 

The v1 search end point has never been reliable, focussed on 'relevance rather than completeness,' whatever that relevance may be.

To get historical tweets these days, you are better of using api V2. Our 4cat tool has capabilities to retrieve all historical data for a query and then export it to TCAT if you so like.

Best,

Erik
