### ISSUE TITLE
issue with installation on Google cloud

### ISSUE THREAD

**Issue by zhanglipku** [digitalmethodsinitiative/dmi-tcat#459]
I set up a Google cloud VM and successfully SSH in from my terminal. When I ran the following command:

curl https://raw.githubusercontent.com/digitalmethodsinitiative/dmi-tcat/master/helpers/tcat-install-linux.sh | sudo bash

I saw the familiar "Choose a tweet capture mode for TCAT to use" language, but it doesn't let me type in a response. Instead, it just gave me an error saying I didn't respond. Please find screenshot.
![Screenshot 2023-05-04 at 6 41 55 PM](https://user-images.githubusercontent.com/17376900/236349898-a13f0917-abdd-465c-95f6-6b93e65b7e48.png)

I  ran into the same issue when installing from my terminal or from the Google cloud console. Any idea?

**Comment by ErikBorra** [comment]
Dear @zhanglipku, 

We are not currently investing in the development of DMI-TCAT because it only supports API v1. Twitter has ceased issuing API v1 keys and has also disabled access using existing keys.

With the release of Twitter API v2 last year, we began to phase out DMI-TCAT development in favor of 4CAT, which now supports Twitter API v2 data access. However, with Musk's purchase of Twitter, it is unclear whether (free) academic access will continue to be possible. We, and other researchers world wide, are currently awaiting any news about that.

If you already have a (still functional) API v2 key, you can try your luck with 4CAT. More information can be found at https://4cat.nl/.

Best regards,

Erik
