### ISSUE TITLE
Use retweeted text instead of (truncated) text

### ISSUE THREAD

**Issue by joelgombin** [digitalmethodsinitiative/dmi-tcat#74]
When an RTed tweet exceed 140 character (including the "RT @user" part), the text is truncated at the end with dots ("..."). So I'd like to suggest that in that case, the `text` field under the `retweeted status` should be used rather than the text from the top level `text` field. (See the `truncated` doc here: [https://dev.twitter.com/overview/api/tweets](https://dev.twitter.com/overview/api/tweets))

**Comment by FlxVctr** [comment]
cc this.
actually it would be pretty easy I think to make no additional field necessary (except there is a 140 character limitation somewhere in TCAT). Test whether the tweet has the attribute retweeted_status, if so fill the field with the text of retweeted_status and add RT @username. In Python (using Tweepy):

if hasattr(tweet, 'retweeted_status'):
        print('RT @'+ tweet.retweeted_status.user.screen_name + ' ' + tweet.retweeted_status.text)
    else:
        print(tweet.text) # instead of print any output function of course

Works well for me if I gather tweets with my own scripts. But don't know (yet) how to implement it here.

**Comment by ErikBorra** [comment]
Good idea, thanks!

**Comment by FlxVctr** [comment]
You're welcome :) Any idea, whether, and if, when you'll implement this in an update? If not, I would edit my instance till you know (or make a fork accessible her, if you don't mind).

**Comment by ErikBorra** [comment]
I am afraid we won't be able to address this in the next two to three weeks, as we are currently very busy with other things. However, we welcome any pull requests!

**Comment by FlxVctr** [comment]
Here you go :)

**Comment by dentoir** [comment]
@FlxVctr thank you for your update and the fix! We're going to implement this, but what to expand on it a little bit. We want to make sure that any retweets with added comment texts in them are not overwritten by the original tweet text. For this purpose we'll add a check to character compare both texts (if there is a retweet) and only exhibit the behaviour of your pull request when the text itself has not been modified.

Additionally we want to change the common/upgrade.php scripts to fix all existing tweets in bin according to the algorithm. We will retrieve the original tweet text from the same bin if the retweeted text is available in there.

I want to experiment whether this works in all cases, but we will push the change soon, as it resolves several issues at once.

**Comment by FlxVctr** [comment]
As I see it, it never gets overwritten, as an edited retweet does not seem to have a retweet_id but an in_reply_to_id, so it gets treated as normal (also cannot exceed 140 characters).
![image](https://cloud.githubusercontent.com/assets/8951994/7769984/ad2509fc-00cc-11e5-899f-d508ac4f0cbf.png)
I rather see a problem with the new method Twitter uses for "quoting" tweets (last tweet in the screenshot). I tested it and if you don't have the keyword in the comment, it won't show up in the collection at all, which means, we lose a lot of retweets. Actually this is a new issue.

**Comment by dentoir** [comment]
Finally an update on this. The issue should be resolved in the latest commit 1a7ce924c6
I've based the changes on your patch @FlxVctr - thanks for that.
I've added the colon character after RT @username because that is how it shows up in the data.

During testing I noticed a new issue. Apparantly the retweeted_status->user->screen_name variable may have a username which is different from the username in the tweet text (with RT @username: ). This is due to the fact that a user may have renamed his screen name and the old screen name is in the retweeted_status, the new one in the tweet text. This actually occurs in most of our bins at least several times. This issue should be fixed by the latest commit as well.

We've decided to go with using the retweeted_status for both text and username. We added a new common/upgrade.php entry which will update the tweet texts in existing bins as in @FlxVctr's patch IF we have stored the original tweet somewhere in the same bin. Also, it will change the usernames to the one in from_user_name if there is a mismatch.

**Comment by FlxVctr** [comment]
Great work! Thx :)

**Comment by dentoir** [comment]
Not for historical purposes: even with the new 280 character limit this change is still relevant. Twitter truncates retweeted tweets when the exceed 280 characters with the RT @someusername prepended to it. We retain the full tweet in the text and this means we may store more than 280 characters in the text field. This behavior is unchanged.
