### ISSUE TITLE
Operator OR doesnt work on search.php

### ISSUE THREAD

**Issue by blackthornecl** [digitalmethodsinitiative/dmi-tcat#76]
I have two hashtags, but when i search at the same time i only get the first one.

**Comment by holnburger** [comment]
Sorry for opening a thread that old, but I experience a similar problem – regarding space-separated phrases and the 'OR' operator.

When I search for: 
$keywords = "'Nachwachsende Rohstoffe'"; 

I get some tweets. But when I search for: 
$keywords = "'Nachhaltige Fischerei' OR 'Nachhaltige Ressourcennutzung' OR 'Nachwachsende Rohstoffe' OR 'Fossile Brennstoffe'"; 
I get no tweets at all – although I should find some tweets at least for 'Nachwachsende Rohstoffe'.

I checked it with several other queries and to me it looks like it's using and AND operator instead of an OR operator when I search for multiple space-separated phrases. Is there a solution for this problem?

**Comment by ErikBorra** [comment]
Hi @holnburger,

try the query without quotes. The TCAT query interface follows mysql logic, not Google logic. I.e. space separated words will be interpreted as a literal string, rather than a set of keywords.

Best,

Erik
