### ISSUE TITLE
Media Content

### ISSUE THREAD

**Issue by psegovias** [digitalmethodsinitiative/dmi-tcat#81]
How i can see the "media" content? i have only links, and url_is_media_upload and media_type always return with 0 or NULL.

I need to extract photos.

Any ideas?

**Comment by dentoir** [comment]
Hi @psegovias 

I'm still curious to find out an example Tweet ID which produces the image retrieval problem for you.
Also, could you execute the following statement on your server (in your www directory) and give us the result?

    git rev-parse HEAD

**Comment by ErikBorra** [comment]
Hi @psegovias,

any update on this?

Best,

Erik

**Comment by psegovias** [comment]
My apology, was on vacation, this week I give news

**Comment by psegovias** [comment]
Hi! im back again:

git rev-parse HEAD
0a491830cde0b5965435c0fde9e9d4162984be18

search track:

#CopaAmerica2015

Tweet id with media:

https://twitter.com/ColNycf/status/565574721899876352

I see the tweet on _tweets but not in _url


Any idea?

**Comment by dentoir** [comment]
Hi @psegovias 

I'm sorry I'm not able to reproduce your issue yet. I'm getting  the photo, including the dimensions, when I do an explicit lookup for your Tweet ID. When I track the hashtag, I get the image data as well.

Do you know the lookup.php script? It is in the capture/ids/ directory. Using this script you can input tweet ids, and the script will look them up and insert them in some bin. Perhaps you can make a list of tweet ids (using export tweet ids function of tcat) and put the numbers in a text file. 

If you put an ids.csv file in this capture/ids directory, with just a tweet ids on every line, you can attempt to get your image data. You need to edit the lookup.php file and set the parameters:

     $bin_name = 'copalookup';    // name of the bin
     $idfile = 'ids.csv';              // path to the input file name. the file must contain only a tweet ID on every line
     $type = 'lookup';               // specify 'lookup'

Then log into your server, head to the capture/ids directory and run: php lookup.php

Requirement: your config.php file should contain at least one valid Twitter API key in the $twitter_keys array.

Hopefully this should produce a new bin called copalookup, with image data. It a good thing to test it anyway, to see if the problem is generic or only track related.

Best,

Emile

**Comment by psegovias** [comment]
I will try, maybe my problem its because im using a cron on search.php and no "track" ? last time i try use the track option, data was missing, like RT, FAV, etc.

**Comment by dentoir** [comment]
Now I was able to reproduce the bug. It looks to me the Search API does not yet support multiple photos in a single tweet (extended entities) yet, as explained here: http://www.leancrew.com/all-this/2014/06/tweets-with-multiple-photos/

We are using the extended entities in tracking (streaming api) and lookups (rest api).
They seems to be missing in the Search API! I haven't found any documentation in relation to this.
For the Search API results we should thus use a different field to get the photo data, it seems. I am now using entities->media.

Your specific issue should be fixed in the latest commit. I would love some feedback if you manage to get results for tweets with _multiple_ photos (I assume not). I've updated the CSV export to contain all image information llike photo dimensions. It seems strange that the result set of the Search API would now be less complete than the tracking API?

**Comment by psegovias** [comment]
@dentoir thanks for your response, but if u see the tweet: https://twitter.com/ColNycf/status/565574721899876352 its only one image, not multiples ones, one images have the same problem on Search API?

**Comment by dentoir** [comment]
Sorry, maybe my explanation was unclear. We did not get the proper image data in search.php, but now we do get all the image data available. So the search.php script should now work in your situation, I hope.

My question is what happens with tweets with multiple photo's. I know this works already in track, but I am not sure it works with search.php now. It might show only the first image. Anyways, we couldn't solve that problem. It would be a platform limitation.

**Comment by psegovias** [comment]
After last pull i got this using the search:

![captura de pantalla 2015-02-13 a las 10 44 05](https://cloud.githubusercontent.com/assets/5105474/6188163/45feb540-b36d-11e4-94a9-800020a2b445.png)


Before i get the url_followed (with urlexpand.py) and domain and error_code.

**Comment by psegovias** [comment]
Nice! i got this now:

![captura de pantalla 2015-02-13 a las 11 16 32](https://cloud.githubusercontent.com/assets/5105474/6188627/daa1b2d4-b371-11e4-968f-d00aa2751a73.png)


If you see, i got the URL from tweet with photo, how i can get the url to .jpg?

**Comment by dentoir** [comment]
This feature should've been implemented by the latest commit. Pull the latest version from git and then execute the upgrade.php script in the common/ directory from the command-line.

If you also want to extract media content (like the raw file url) for older tweets in the bin, you will need to run the script upgrade-media.php from within the same directory. This may take a while depending on the size of your query bins.

I hope this solution works for you.

**Comment by psegovias** [comment]
works great!
